version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    network_mode: host

  server:
    image: server
    container_name: server_container
    depends_on:
      - redis
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    network_mode: host

